name: Update Posts

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-posts:
    name: Update Posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://blog-gh.cpen.top/atom.xml"
          max_post_count: "3"
          commit_message: "chore: update blog posts"
          committer_username: "github-actions[bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"
